SELECT 
    H.CAR_ID, 
    IF(M.MAX_DATE >= '2022-10-16', '대여중', '대여 가능') AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN (SELECT CAR_ID, MAX(END_DATE) AS MAX_DATE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE <= '2022-10-16'
 GROUP BY CAR_ID
) M ON H.CAR_ID = M.CAR_ID AND M.MAX_DATE = H.END_DATE
ORDER BY M.CAR_ID DESC