SELECT 
    F.ID,
    I.FISH_NAME,
    F.LENGTH
FROM FISH_NAME_INFO I
JOIN FISH_INFO F 
  ON I.FISH_TYPE = F.FISH_TYPE
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) M 
  ON F.FISH_TYPE = M.FISH_TYPE AND F.LENGTH = M.MAX_LENGTH;